import type { CmsData } from "./cms-types";

const portalUrl = "https://vertibis-frontend.vercel.app";

export const defaultCmsData: CmsData = {
  settings: {
    companyName: "Vertibis Technologies Pvt Ltd",
    footerCopy:
      "Vertibis is building an explainable MSME Business Health Intelligence ecosystem for Indian MSMEs, CAs, lenders, insurers and enterprises.",
    contactEmail: "hello@vertibis.com",
    registeredLocation: "India",
    linkedInUrl: "https://www.linkedin.com/company/vertibis",
    loginUrl: portalUrl,
    partnerJoinUrl: portalUrl,
    msmEpilotUrl: "/contact?type=msme-pilot",
    institutionalContactUrl: "/contact?type=institutional",
    seoTitle: "Vertibis | MSME Business Health Intelligence Ecosystem",
    seoDescription:
      "Vertibis is building an explainable MSME Health Intelligence ecosystem for CAs, MSMEs, lenders, insurers and enterprises.",
    announcementBanner:
      "CA Partner Pilot open. GST API integration is in testing through the Registered ASP pathway with TaxPro GSTP.",
    gstDisclaimer:
      "Vertibis is a Registered ASP with TaxPro GSTP. GST API integration is currently under testing/pilot stage and will be enabled subject to applicable approvals, consent workflows and technical readiness.",
    platformDisclaimer:
      "Vertibis is an AI-assisted business intelligence and professional productivity platform. Outputs are indicative, explainable and based on available information. They should not be treated as final legal, tax, credit, investment or insurance advice without professional review.",
  },
  navigation: [
    { label: "Home", href: "/", showInHeader: true, showInFooter: true },
    { label: "For CAs", href: "/for-cas", showInHeader: true, showInFooter: true },
    { label: "For MSMEs", href: "/for-msmes", showInHeader: true, showInFooter: true },
    { label: "For Lenders", href: "/for-lenders", showInHeader: true, showInFooter: true },
    { label: "For Enterprises", href: "/for-enterprises", showInHeader: true, showInFooter: true },
    { label: "For Insurance", href: "/for-insurance", showInHeader: true, showInFooter: true },
    { label: "Pricing", href: "/pricing", showInHeader: true, showInFooter: true },
    { label: "Resources", href: "/resources", showInHeader: true, showInFooter: true },
    { label: "About", href: "/about", showInHeader: true, showInFooter: true },
    { label: "Contact", href: "/contact", showInHeader: true, showInFooter: true },
  ],
  websiteStats: [
    {
      label: "CA Partner Pilot",
      value: "Open",
      description: "Pilot onboarding is active for selected CA, CS and tax-consultant partners.",
      isReal: true,
      isDemo: false,
      display: true,
      sourceNote: "Internal pilot status",
      lastUpdated: "2026-07-08",
    },
    {
      label: "GST API Stage",
      value: "Testing",
      description: "GST API workflows are being tested through the ASP/GSP pathway.",
      isReal: true,
      isDemo: false,
      display: true,
      sourceNote: "Registered ASP with TaxPro GSTP",
      lastUpdated: "2026-07-08",
    },
    {
      label: "MSME Health Reports",
      value: "Pilot",
      description: "Report workflows are being prepared for pilot-stage MSME and partner use.",
      isReal: true,
      isDemo: false,
      display: true,
      sourceNote: "Product-stage label, not traction claim",
      lastUpdated: "2026-07-08",
    },
  ],
  homepage: {
    heroHeadline: "The Backbone of Business Health",
    heroSubheadline:
      "Vertibis is building an explainable MSME Business Health Intelligence ecosystem for businesses, CAs, lenders, insurers and enterprises.",
    heroSupportingText:
      "We convert fragmented GST, financial, compliance and business signals into actionable business-health insights, loan-readiness indicators, advisory opportunities and risk intelligence.",
    badges: [
      "Registered ASP with TaxPro GSTP",
      "GST API Testing in Progress",
      "CA Partner Pilot Open",
      "MSME Health Reports Coming Soon",
    ],
    primaryCta: { label: "Join CA Partner Programme", href: portalUrl, variant: "primary" },
    secondaryCta: { label: "Explore MSME Health Score", href: "/for-msmes", variant: "secondary" },
    tertiaryCta: {
      label: "Talk to Us for Institutional Use Cases",
      href: "/contact?type=institutional",
      variant: "ghost",
    },
    problemCards: [
      "MSMEs generate GST, income-tax, banking and compliance data, but rarely get a unified business-health view.",
      "CAs handle compliance but need tools to convert data into advisory opportunities.",
      "Lenders need explainable MSME risk and loan-readiness intelligence.",
      "Enterprises need vendor-health monitoring beyond onboarding.",
      "Insurers need better MSME business-risk indicators.",
    ],
    ecosystemLayers: [
      {
        name: "CA Intelligence and Growth",
        description: "CAs are the trusted advisory layer that helps MSMEs understand and act on business-health signals.",
        items: [
          "Client portfolio insights",
          "Health reports",
          "Compliance intelligence",
          "Advisory opportunities",
          "Client communication",
          "CA practice growth",
        ],
      },
      {
        name: "MSME Business Health",
        description: "MSMEs get explainable scores, risk reasons and improvement recommendations before others judge them.",
        items: [
          "Business Health Score",
          "GST health",
          "Financial stability",
          "Cash-flow indicators",
          "Loan readiness",
          "Improvement recommendations",
        ],
      },
      {
        name: "Institutional Intelligence",
        description: "Banks, NBFCs, enterprises and insurers can use consent-backed signals for better portfolio workflows.",
        items: [
          "Lender risk support",
          "Vendor health monitoring",
          "Insurance risk indicators",
          "Early-warning signals",
          "Score APIs",
          "Portfolio monitoring",
        ],
      },
    ],
    trustItems: [
      "Client consent workflow",
      "Data minimisation",
      "GST API testing through Registered ASP with TaxPro GSTP",
      "Explainable scoring factors",
      "Data freshness indicators",
      "Audit trail",
      "Professional review before advisory output",
      "DPDP-conscious design approach",
      "Secure integrations roadmap",
    ],
    pilotAudiences: [
      {
        title: "CA / CS / Tax Consultant",
        description: "Join the early partner programme and generate consent-backed MSME health reports.",
        formId: "ca-partner",
        cta: { label: "Become a Vertibis Partner", href: "/contact?type=ca-partner", variant: "primary" },
      },
      {
        title: "MSME Owner",
        description: "Request a pilot report to understand business health, risk areas and loan readiness.",
        formId: "msme-pilot",
        cta: { label: "Request MSME Pilot", href: "/contact?type=msme-pilot", variant: "secondary" },
      },
      {
        title: "Bank / NBFC / Fintech",
        description: "Discuss loan-readiness, early-warning and borrower-monitoring use cases.",
        formId: "lender-interest",
        cta: { label: "Discuss Lender Use Case", href: "/contact?type=lender", variant: "secondary" },
      },
      {
        title: "Enterprise / Insurance / Strategic Partner",
        description: "Explore vendor-health, insurance-risk and ecosystem intelligence opportunities.",
        formId: "institutional-interest",
        cta: { label: "Explore Institutional Pilot", href: "/contact?type=institutional", variant: "secondary" },
      },
    ],
  },
  audiencePages: {
    cas: {
      eyebrow: "For CAs, CSs and tax consultants",
      title: "Help clients better. Grow your practice faster.",
      description:
        "Vertibis positions CAs as the trusted distribution and review layer for MSME business-health intelligence.",
      primaryCta: { label: "Become a Vertibis Partner", href: portalUrl, variant: "primary" },
      secondaryCta: { label: "Talk to Partner Team", href: "/contact?type=ca-partner", variant: "secondary" },
      sections: [
        {
          title: "Why CAs are central",
          description:
            "MSME owners already trust their CA for compliance, interpretation and decisions. Vertibis helps convert that trust into structured advisory conversations.",
          points: [
            "Generate MSME Health Reports",
            "Use client consent workflows",
            "Review explainable advisory output before client use",
            "Create co-branded reports",
          ],
        },
        {
          title: "Partner workflow",
          description:
            "Add client, collect consent, generate a pilot report, review recommendations and use the output for advisory or financing conversations.",
          points: [
            "GST API testing through ASP/GSP pathway",
            "Portfolio dashboard roadmap",
            "Report credits and partner pricing",
            "Future CA Intelligence Dashboard",
          ],
        },
      ],
    },
    msmes: {
      eyebrow: "For MSMEs",
      title: "Know your business health before others judge it.",
      description:
        "The MSME Health Report helps business owners understand financial, compliance and operating health in a language they can act on.",
      primaryCta: { label: "Request MSME Health Report Pilot", href: "/contact?type=msme-pilot", variant: "primary" },
      secondaryCta: { label: "See Report Coverage", href: "/pricing#report-pricing", variant: "secondary" },
      sections: [
        {
          title: "What the report may cover",
          description:
            "A pilot-stage report may combine GST, financial, compliance and business indicators into an explainable health view.",
          points: [
            "Business Health Score",
            "GST and compliance health",
            "Financial stability",
            "Cash-flow indicators",
            "Loan readiness",
            "Improvement recommendations",
          ],
        },
        {
          title: "How to request",
          description:
            "Reports can be requested through a participating CA partner or directly through the MSME pilot workflow.",
          points: [
            "Consent-backed data use",
            "Professional review encouraged",
            "Share structured reports with CA, lender or investor",
            "Track health trends over time",
          ],
        },
      ],
    },
    lenders: {
      eyebrow: "For banks, NBFCs and fintechs",
      title: "Explainable MSME intelligence for lending support.",
      description:
        "Vertibis does not approve or reject loans. It supports pre-lending and monitoring workflows with explainable MSME intelligence.",
      primaryCta: { label: "Discuss Lender Use Case", href: "/contact?type=lender", variant: "primary" },
      secondaryCta: { label: "Explore MSME Health Score", href: "/for-msmes", variant: "secondary" },
      sections: [
        {
          title: "The lending information gap",
          description:
            "MSME credit conversations often lack clean, explainable, current business-health context.",
          points: [
            "Loan-readiness assessment",
            "Pre-lending support",
            "Early-warning indicators",
            "Borrower monitoring",
          ],
        },
        {
          title: "Institutional roadmap",
          description:
            "Future APIs and dashboards can support consent-backed portfolio workflows when technical and regulatory readiness is complete.",
          points: [
            "Consent-backed data access",
            "Portfolio health trends",
            "Business improvement tracking",
            "API and dashboard roadmap",
          ],
        },
      ],
    },
    enterprises: {
      eyebrow: "For enterprises",
      title: "Monitor vendor health beyond onboarding.",
      description:
        "Vertibis can support supplier health, periodic vendor checks and supply-chain early-warning workflows.",
      primaryCta: { label: "Explore Vendor Health", href: "/contact?type=enterprise", variant: "primary" },
      secondaryCta: { label: "See Product Modules", href: "/#modules", variant: "secondary" },
      sections: [
        {
          title: "Vendor risk problem",
          description:
            "Vendor onboarding captures documents once, but supplier health changes continuously.",
          points: [
            "Vendor onboarding intelligence",
            "Supplier risk segmentation",
            "Periodic vendor health check",
            "Compliance and financial-health signals",
          ],
        },
        {
          title: "Vendor development",
          description:
            "Use explainable reports to help suppliers improve, not only to flag risk.",
          points: [
            "Supply-chain early warning",
            "Vendor improvement recommendations",
            "Portfolio health monitoring",
            "Enterprise pilot interest workflow",
          ],
        },
      ],
    },
    insurance: {
      eyebrow: "For insurance",
      title: "MSME business-risk indicators for insurance intelligence.",
      description:
        "Vertibis can support underwriting and portfolio workflows with consent-backed business continuity, compliance and financial-health indicators.",
      primaryCta: { label: "Explore Insurance Use Case", href: "/contact?type=insurance", variant: "primary" },
      secondaryCta: { label: "Talk to Us", href: "/contact", variant: "secondary" },
      sections: [
        {
          title: "MSME insurance information gap",
          description:
            "Insurance workflows need better business-risk indicators without pretending one score can replace expert judgement.",
          points: [
            "Business continuity signals",
            "Compliance behaviour",
            "Financial-stability indicators",
            "Cash-flow stress signals",
          ],
        },
        {
          title: "Risk intelligence roadmap",
          description:
            "Pilot-stage indicators can help segment MSME business risk and support underwriting review.",
          points: [
            "Risk segmentation",
            "Underwriting support",
            "Periodic health refresh",
            "Insurance pilot form",
          ],
        },
      ],
    },
  },
  productModules: [
    {
      name: "MSME Health Score",
      description: "Explainable composite health view across compliance, financial and business signals.",
      audience: "MSME, CA, Lender",
      stage: "pilot",
      icon: "HS",
      displayOrder: 1,
      relatedCta: { label: "Explore", href: "/for-msmes", variant: "secondary" },
      show: true,
    },
    {
      name: "GST Health Analysis",
      description: "GST filing and compliance indicators under testing through the ASP/GSP pathway.",
      audience: "MSME, CA",
      stage: "testing",
      icon: "GST",
      displayOrder: 2,
      relatedCta: { label: "See status", href: "/about#gst-status", variant: "secondary" },
      show: true,
    },
    {
      name: "Financial Stability",
      description: "Stability indicators designed for professional review and MSME improvement planning.",
      audience: "MSME, CA, Lender",
      stage: "pilot",
      icon: "FS",
      displayOrder: 3,
      relatedCta: { label: "Learn more", href: "/for-msmes", variant: "secondary" },
      show: true,
    },
    {
      name: "Cash-flow Intelligence",
      description: "Cash-flow stress and working-capital indicators for advisory workflows.",
      audience: "MSME, CA",
      stage: "planned",
      icon: "CF",
      displayOrder: 4,
      relatedCta: { label: "Join pilot", href: "/contact?type=msme-pilot", variant: "secondary" },
      show: true,
    },
    {
      name: "Loan Readiness",
      description: "Decision-support signals for preparation and monitoring, not loan approval.",
      audience: "MSME, Lender",
      stage: "pilot",
      icon: "LR",
      displayOrder: 5,
      relatedCta: { label: "For lenders", href: "/for-lenders", variant: "secondary" },
      show: true,
    },
    {
      name: "CA Partner Dashboard",
      description: "Partner workflow for client reports, credits, portfolio insights and advisory opportunities.",
      audience: "CA",
      stage: "pilot",
      icon: "CA",
      displayOrder: 6,
      relatedCta: { label: "Partner login", href: portalUrl, variant: "secondary" },
      show: true,
    },
    {
      name: "Vendor Health",
      description: "Supplier-health monitoring for onboarding and periodic enterprise risk review.",
      audience: "Enterprise",
      stage: "planned",
      icon: "VH",
      displayOrder: 7,
      relatedCta: { label: "Explore", href: "/for-enterprises", variant: "secondary" },
      show: true,
    },
    {
      name: "Lender Intelligence",
      description: "Portfolio and borrower intelligence roadmap for banks, NBFCs and fintechs.",
      audience: "Lender",
      stage: "planned",
      icon: "LI",
      displayOrder: 8,
      relatedCta: { label: "Discuss", href: "/contact?type=lender", variant: "secondary" },
      show: true,
    },
    {
      name: "Insurance Risk Indicators",
      description: "Business-risk indicators for insurance underwriting and portfolio review support.",
      audience: "Insurance",
      stage: "planned",
      icon: "IR",
      displayOrder: 9,
      relatedCta: { label: "Explore", href: "/for-insurance", variant: "secondary" },
      show: true,
    },
    {
      name: "Future Score API",
      description: "API roadmap for strategic partners after consent, security and production readiness.",
      audience: "Institutional",
      stage: "planned",
      icon: "API",
      displayOrder: 10,
      relatedCta: { label: "Contact", href: "/contact?type=institutional", variant: "secondary" },
      show: true,
    },
  ],
  pricingPlans: [
    {
      name: "Starter Partner",
      audienceType: "ca_partner",
      price: "Rs 3,999",
      billingPeriod: "per year",
      description: "For solo practitioners and small advisory practices joining the pilot.",
      features: [
        "Partner intelligence dashboard",
        "Pilot client workflow",
        "Client consent workflow",
        "Report credit wallet",
        "Co-branded client reports",
      ],
      highlighted: false,
      cta: { label: "Join Pilot", href: portalUrl, variant: "primary" },
      status: "pilot",
      displayOrder: 1,
    },
    {
      name: "Firm Partner",
      audienceType: "ca_partner",
      price: "Rs 7,999",
      billingPeriod: "per year",
      description: "For CA, CS, CWA, advocate and tax-consultant firms managing a larger base.",
      features: [
        "Everything in Starter",
        "Advanced portfolio analytics roadmap",
        "Opportunity pipeline tracking",
        "Pitch and proposal tools",
        "Priority partner support",
      ],
      highlighted: true,
      cta: { label: "Start Firm Pilot", href: portalUrl, variant: "primary" },
      status: "pilot",
      displayOrder: 2,
    },
    {
      name: "Growth Partner",
      audienceType: "ca_partner",
      price: "Rs 12,999",
      billingPeriod: "per year",
      description: "For larger practices and teams preparing for deeper operating visibility.",
      features: [
        "Everything in Firm",
        "Large client portfolio support",
        "White-label report options roadmap",
        "Team workflow readiness",
        "Custom onboarding support",
      ],
      highlighted: false,
      cta: { label: "Talk to Partner Team", href: "/contact?type=ca-partner", variant: "secondary" },
      status: "pilot",
      displayOrder: 3,
    },
    {
      name: "Institutional",
      audienceType: "strategic_partner",
      price: "Custom",
      billingPeriod: "pilot discussion",
      description: "For banks, NBFCs, enterprises, insurers and strategic platform partners.",
      features: [
        "Institutional use-case mapping",
        "API and dashboard roadmap",
        "Consent-backed pilot design",
        "Security and data-flow review",
        "Custom commercial discussion",
      ],
      highlighted: false,
      cta: { label: "Discuss Institutional Use", href: "/contact?type=institutional", variant: "secondary" },
      status: "pilot",
      displayOrder: 4,
    },
  ],
  reportPricing: [
    {
      name: "Quick Health Snapshot",
      price: "Rs 499",
      description: "For first client conversations and portal workflow testing.",
      stage: "pilot",
      displayOrder: 1,
    },
    {
      name: "Annual Health Report",
      price: "Rs 999 / 1,999 / 2,999",
      description: "FY-focused report pricing based on turnover band.",
      stage: "pilot",
      displayOrder: 2,
    },
    {
      name: "Detailed Business Health Report",
      price: "Rs 1,499 / 2,499 / 3,499",
      description: "Final scoring report with advisory and action plan. Pricing varies by turnover band.",
      stage: "pilot",
      displayOrder: 3,
    },
    {
      name: "Loan Readiness Add-on",
      price: "Pilot discussion",
      description: "Add-on report layer for lender-readiness conversations.",
      stage: "planned",
      displayOrder: 4,
    },
    {
      name: "Vendor Health Add-on",
      price: "Pilot discussion",
      description: "Add-on report layer for enterprise vendor-health workflows.",
      stage: "planned",
      displayOrder: 5,
    },
  ],
  leadForms: [
    {
      id: "ca-partner",
      name: "CA Partner Form",
      audienceType: "ca_partner",
      fields: [
        { name: "name", label: "Name", type: "text", required: true, placeholder: "Your name" },
        { name: "email", label: "Email", type: "email", required: true, placeholder: "you@firm.com" },
        { name: "phone", label: "Phone", type: "tel", required: true, placeholder: "+91" },
        { name: "organisation", label: "Firm / organisation", type: "text", required: true, placeholder: "Firm name" },
        { name: "city", label: "City", type: "text", required: true, placeholder: "Mumbai" },
        { name: "message", label: "Message", type: "textarea", required: false, placeholder: "Tell us about your client base." },
      ],
      consentText: "I consent to Vertibis contacting me about the CA Partner Pilot.",
      successMessage: "Thanks. The Vertibis partner team will get back to you shortly.",
      notificationEmail: "hello@vertibis.com",
      active: true,
    },
    {
      id: "msme-pilot",
      name: "MSME Pilot Form",
      audienceType: "msme",
      fields: [
        { name: "name", label: "Name", type: "text", required: true, placeholder: "Your name" },
        { name: "email", label: "Email", type: "email", required: true, placeholder: "you@business.com" },
        { name: "phone", label: "Phone", type: "tel", required: true, placeholder: "+91" },
        { name: "organisation", label: "Business name", type: "text", required: true, placeholder: "Your MSME" },
        { name: "city", label: "City", type: "text", required: false, placeholder: "Ahmedabad" },
        { name: "message", label: "What do you want to understand?", type: "textarea", required: false, placeholder: "Loan readiness, compliance health, cash-flow stress..." },
      ],
      consentText: "I consent to Vertibis contacting me about the MSME Health Report Pilot.",
      successMessage: "Thanks. We will contact you about the MSME Health Report Pilot.",
      notificationEmail: "hello@vertibis.com",
      active: true,
    },
    {
      id: "lender-interest",
      name: "Lender Interest Form",
      audienceType: "lender",
      fields: [
        { name: "name", label: "Name", type: "text", required: true, placeholder: "Your name" },
        { name: "email", label: "Work email", type: "email", required: true, placeholder: "you@institution.com" },
        { name: "organisation", label: "Institution", type: "text", required: true, placeholder: "Bank / NBFC / Fintech" },
        { name: "role", label: "Role", type: "text", required: false, placeholder: "Risk, credit, product..." },
        { name: "message", label: "Use case", type: "textarea", required: true, placeholder: "Tell us about the lending workflow." },
      ],
      consentText: "I consent to Vertibis contacting me about institutional MSME intelligence use cases.",
      successMessage: "Thanks. We will follow up to discuss lender use cases.",
      notificationEmail: "hello@vertibis.com",
      active: true,
    },
    {
      id: "enterprise-interest",
      name: "Enterprise Interest Form",
      audienceType: "enterprise",
      fields: [
        { name: "name", label: "Name", type: "text", required: true, placeholder: "Your name" },
        { name: "email", label: "Work email", type: "email", required: true, placeholder: "you@enterprise.com" },
        { name: "organisation", label: "Company", type: "text", required: true, placeholder: "Company name" },
        { name: "message", label: "Vendor-health need", type: "textarea", required: true, placeholder: "Tell us about your supplier or vendor monitoring need." },
      ],
      consentText: "I consent to Vertibis contacting me about vendor-health intelligence.",
      successMessage: "Thanks. We will follow up on vendor-health use cases.",
      notificationEmail: "hello@vertibis.com",
      active: true,
    },
    {
      id: "insurance-interest",
      name: "Insurance Interest Form",
      audienceType: "insurance",
      fields: [
        { name: "name", label: "Name", type: "text", required: true, placeholder: "Your name" },
        { name: "email", label: "Work email", type: "email", required: true, placeholder: "you@insurance.com" },
        { name: "organisation", label: "Organisation", type: "text", required: true, placeholder: "Insurer / broker / partner" },
        { name: "message", label: "Insurance use case", type: "textarea", required: true, placeholder: "Tell us about underwriting or risk indicator needs." },
      ],
      consentText: "I consent to Vertibis contacting me about insurance-risk intelligence.",
      successMessage: "Thanks. We will follow up on insurance use cases.",
      notificationEmail: "hello@vertibis.com",
      active: true,
    },
    {
      id: "general-contact",
      name: "General Contact Form",
      audienceType: "general",
      fields: [
        { name: "name", label: "Name", type: "text", required: true, placeholder: "Your name" },
        { name: "email", label: "Email", type: "email", required: true, placeholder: "you@example.com" },
        { name: "organisation", label: "Organisation", type: "text", required: false, placeholder: "Optional" },
        { name: "message", label: "Message", type: "textarea", required: true, placeholder: "How can we help?" },
      ],
      consentText: "I consent to Vertibis contacting me about this enquiry.",
      successMessage: "Thanks. We will get back to you shortly.",
      notificationEmail: "hello@vertibis.com",
      active: true,
    },
  ],
  testimonials: [
    {
      name: "Pilot participant",
      designation: "CA Partner",
      organisation: "Demo firm",
      quote:
        "This is placeholder testimonial copy for internal review only. It is intentionally hidden from the public website.",
      permissionReceived: false,
      isDemo: true,
      show: false,
    },
  ],
  resources: [
    {
      title: "What is an MSME Business Health Score?",
      slug: "what-is-msme-business-health-score",
      category: "MSME Health Score",
      author: "Vertibis Team",
      summary:
        "A draft explainer on why MSMEs need unified, explainable business-health intelligence.",
      body:
        "This draft resource will explain the concept of business-health scoring, its limitations, and how professional review fits into the workflow.",
      seoTitle: "What is an MSME Business Health Score? | Vertibis",
      seoDescription: "Learn how an explainable MSME Business Health Score can support owners and advisors.",
      status: "published",
      publishDate: "2026-07-08",
    },
    {
      title: "CA Practice Intelligence: From Compliance to Advisory",
      slug: "ca-practice-intelligence",
      category: "CA Practice Intelligence",
      author: "Vertibis Team",
      summary:
        "Coming-soon resource on how CAs can use report-led workflows to identify advisory opportunities.",
      body:
        "This coming-soon article will cover CA partner workflows, client consent, co-branded reports and practice-growth opportunities.",
      seoTitle: "CA Practice Intelligence | Vertibis",
      seoDescription: "How CAs can move from compliance-only workflows to report-led advisory.",
      status: "draft",
      publishDate: "2026-07-08",
    },
    {
      title: "Loan Readiness Is Not Loan Approval",
      slug: "loan-readiness-is-not-loan-approval",
      category: "Loan Readiness",
      author: "Vertibis Team",
      summary:
        "A careful distinction between decision-support indicators and regulated credit decisions.",
      body:
        "Vertibis loan-readiness indicators are designed to support preparation and review. They do not approve, reject or guarantee credit.",
      seoTitle: "MSME Loan Readiness and Risk Intelligence | Vertibis",
      seoDescription: "Understand the difference between loan-readiness support and credit approval.",
      status: "published",
      publishDate: "2026-07-08",
    },
  ],
  faqs: [
    {
      question: "What is Vertibis?",
      answer:
        "Vertibis is building an explainable MSME Business Health Intelligence ecosystem for CAs, MSMEs, lenders, insurers and enterprises.",
      category: "general",
      show: true,
    },
    {
      question: "Is GST API integration live?",
      answer:
        "Vertibis is a Registered ASP with TaxPro GSTP. GST API integration is currently in testing/pilot stage and will be enabled subject to applicable approvals, consent workflows and technical readiness.",
      category: "trust",
      show: true,
    },
    {
      question: "Does Vertibis approve loans?",
      answer:
        "No. Vertibis may provide loan-readiness indicators and decision-support intelligence, but it does not approve, reject or guarantee loans.",
      category: "lenders",
      show: true,
    },
    {
      question: "Are the public stats verified?",
      answer:
        "Only pilot-stage and product-stage labels are displayed publicly. Demo or placeholder metrics are hidden unless explicitly marked as pilot language.",
      category: "trust",
      show: true,
    },
  ],
};
